/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as McpsRouteImport } from './routes/mcps'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposIdRouteImport } from './routes/repos.$id'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const McpsRoute = McpsRouteImport.update({
  id: '/mcps',
  path: '/mcps',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIdRoute = ReposIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReposRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mcps': typeof McpsRoute
  '/repos': typeof ReposRouteWithChildren
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/repos/$id': typeof ReposIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mcps': typeof McpsRoute
  '/repos': typeof ReposRouteWithChildren
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/repos/$id': typeof ReposIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mcps': typeof McpsRoute
  '/repos': typeof ReposRouteWithChildren
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/repos/$id': typeof ReposIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/mcps'
    | '/repos'
    | '/runs'
    | '/settings'
    | '/skills'
    | '/repos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/mcps'
    | '/repos'
    | '/runs'
    | '/settings'
    | '/skills'
    | '/repos/$id'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/mcps'
    | '/repos'
    | '/runs'
    | '/settings'
    | '/skills'
    | '/repos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  McpsRoute: typeof McpsRoute
  ReposRoute: typeof ReposRouteWithChildren
  RunsRoute: typeof RunsRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcps': {
      id: '/mcps'
      path: '/mcps'
      fullPath: '/mcps'
      preLoaderRoute: typeof McpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$id': {
      id: '/repos/$id'
      path: '/$id'
      fullPath: '/repos/$id'
      preLoaderRoute: typeof ReposIdRouteImport
      parentRoute: typeof ReposRoute
    }
  }
}

interface ReposRouteChildren {
  ReposIdRoute: typeof ReposIdRoute
}

const ReposRouteChildren: ReposRouteChildren = {
  ReposIdRoute: ReposIdRoute,
}

const ReposRouteWithChildren = ReposRoute._addFileChildren(ReposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  McpsRoute: McpsRoute,
  ReposRoute: ReposRouteWithChildren,
  RunsRoute: RunsRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
