/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as McpsRouteImport } from './routes/mcps'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TriggersIndexRouteImport } from './routes/triggers.index'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as TriggersNewRouteImport } from './routes/triggers.new'
import { Route as TriggersIdRouteImport } from './routes/triggers.$id'
import { Route as RunsIdRouteImport } from './routes/runs.$id'
import { Route as ReposIdRouteImport } from './routes/repos.$id'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const McpsRoute = McpsRouteImport.update({
  id: '/mcps',
  path: '/mcps',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TriggersIndexRoute = TriggersIndexRouteImport.update({
  id: '/triggers/',
  path: '/triggers/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TriggersNewRoute = TriggersNewRouteImport.update({
  id: '/triggers/new',
  path: '/triggers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TriggersIdRoute = TriggersIdRouteImport.update({
  id: '/triggers/$id',
  path: '/triggers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIdRoute = ReposIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReposRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/login': typeof LoginRoute
  '/mcps': typeof McpsRoute
  '/repos': typeof ReposRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/usage': typeof UsageRoute
  '/repos/$id': typeof ReposIdRoute
  '/runs/$id': typeof RunsIdRoute
  '/triggers/$id': typeof TriggersIdRoute
  '/triggers/new': typeof TriggersNewRoute
  '/runs/': typeof RunsIndexRoute
  '/triggers/': typeof TriggersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/login': typeof LoginRoute
  '/mcps': typeof McpsRoute
  '/repos': typeof ReposRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/usage': typeof UsageRoute
  '/repos/$id': typeof ReposIdRoute
  '/runs/$id': typeof RunsIdRoute
  '/triggers/$id': typeof TriggersIdRoute
  '/triggers/new': typeof TriggersNewRoute
  '/runs': typeof RunsIndexRoute
  '/triggers': typeof TriggersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/login': typeof LoginRoute
  '/mcps': typeof McpsRoute
  '/repos': typeof ReposRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/usage': typeof UsageRoute
  '/repos/$id': typeof ReposIdRoute
  '/runs/$id': typeof RunsIdRoute
  '/triggers/$id': typeof TriggersIdRoute
  '/triggers/new': typeof TriggersNewRoute
  '/runs/': typeof RunsIndexRoute
  '/triggers/': typeof TriggersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/doctor'
    | '/login'
    | '/mcps'
    | '/repos'
    | '/settings'
    | '/skills'
    | '/usage'
    | '/repos/$id'
    | '/runs/$id'
    | '/triggers/$id'
    | '/triggers/new'
    | '/runs/'
    | '/triggers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/doctor'
    | '/login'
    | '/mcps'
    | '/repos'
    | '/settings'
    | '/skills'
    | '/usage'
    | '/repos/$id'
    | '/runs/$id'
    | '/triggers/$id'
    | '/triggers/new'
    | '/runs'
    | '/triggers'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/doctor'
    | '/login'
    | '/mcps'
    | '/repos'
    | '/settings'
    | '/skills'
    | '/usage'
    | '/repos/$id'
    | '/runs/$id'
    | '/triggers/$id'
    | '/triggers/new'
    | '/runs/'
    | '/triggers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  DoctorRoute: typeof DoctorRoute
  LoginRoute: typeof LoginRoute
  McpsRoute: typeof McpsRoute
  ReposRoute: typeof ReposRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  UsageRoute: typeof UsageRoute
  RunsIdRoute: typeof RunsIdRoute
  TriggersIdRoute: typeof TriggersIdRoute
  TriggersNewRoute: typeof TriggersNewRoute
  RunsIndexRoute: typeof RunsIndexRoute
  TriggersIndexRoute: typeof TriggersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcps': {
      id: '/mcps'
      path: '/mcps'
      fullPath: '/mcps'
      preLoaderRoute: typeof McpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triggers/': {
      id: '/triggers/'
      path: '/triggers'
      fullPath: '/triggers/'
      preLoaderRoute: typeof TriggersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triggers/new': {
      id: '/triggers/new'
      path: '/triggers/new'
      fullPath: '/triggers/new'
      preLoaderRoute: typeof TriggersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triggers/$id': {
      id: '/triggers/$id'
      path: '/triggers/$id'
      fullPath: '/triggers/$id'
      preLoaderRoute: typeof TriggersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$id': {
      id: '/repos/$id'
      path: '/$id'
      fullPath: '/repos/$id'
      preLoaderRoute: typeof ReposIdRouteImport
      parentRoute: typeof ReposRoute
    }
  }
}

interface ReposRouteChildren {
  ReposIdRoute: typeof ReposIdRoute
}

const ReposRouteChildren: ReposRouteChildren = {
  ReposIdRoute: ReposIdRoute,
}

const ReposRouteWithChildren = ReposRoute._addFileChildren(ReposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  DoctorRoute: DoctorRoute,
  LoginRoute: LoginRoute,
  McpsRoute: McpsRoute,
  ReposRoute: ReposRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  UsageRoute: UsageRoute,
  RunsIdRoute: RunsIdRoute,
  TriggersIdRoute: TriggersIdRoute,
  TriggersNewRoute: TriggersNewRoute,
  RunsIndexRoute: RunsIndexRoute,
  TriggersIndexRoute: TriggersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
