import { Button } from "@sentry-fixer-bot/ui/components/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@sentry-fixer-bot/ui/components/card";
import { Input } from "@sentry-fixer-bot/ui/components/input";
import { Label } from "@sentry-fixer-bot/ui/components/label";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { Play, Zap } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

import { trpc } from "@/utils/trpc";

export const Route = createFileRoute("/runs")({
  component: RunsPage,
});

function RunsPage() {
  const qc = useQueryClient();
  const list = useQuery(trpc.runs.list.queryOptions({ limit: 50 }));
  const [issue, setIssue] = useState("");
  const trigger = useMutation(
    trpc.runs.triggerMock.mutationOptions({
      onSuccess: (r) => {
        toast.success(`Queued triage for ${r.sentryProject}: ${r.title.slice(0, 60)}`);
        setIssue("");
        qc.invalidateQueries({ queryKey: trpc.runs.list.queryKey() });
      },
      onError: (err) => toast.error(err.message),
    }),
  );

  const rows = list.data ?? [];

  return (
    <div className="mx-auto flex max-w-5xl flex-col gap-6 p-6">
      <header>
        <h1 className="font-semibold text-2xl">Runs</h1>
        <p className="text-sm text-zinc-500">
          Auto-generated by the Sentry webhook / cron. Use the form below to dry-run the pipeline
          against a specific issue without waiting for a real alert.
        </p>
      </header>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <Zap className="h-4 w-4" /> Trigger a run from a Sentry issue
          </CardTitle>
          <CardDescription>
            Paste a Sentry issue URL or numeric id. The server fetches the issue via the Sentry API,
            writes an alert row, and enqueues the triage job — same code path the real webhook uses.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-2">
          <Label htmlFor="issue">Sentry issue URL / id</Label>
          <div className="flex gap-2">
            <Input
              id="issue"
              value={issue}
              onChange={(e) => setIssue(e.target.value)}
              placeholder="https://your-org.sentry.io/issues/7340544098/  or  7340544098"
            />
            <Button
              disabled={!issue.trim() || trigger.isPending}
              onClick={() => trigger.mutate({ issue: issue.trim() })}
            >
              <Play className="mr-1.5 h-4 w-4" />
              {trigger.isPending ? "Queuing…" : "Trigger"}
            </Button>
          </div>
        </CardContent>
      </Card>

      {list.isLoading ? (
        <p className="text-sm text-zinc-500">Loading…</p>
      ) : list.error ? (
        <p className="text-red-300 text-sm">{list.error.message}</p>
      ) : rows.length === 0 ? (
        <p className="rounded-md border border-dashed p-8 text-center text-sm text-zinc-500">
          No runs yet. Trigger one above or wait for the next cron tick.
        </p>
      ) : (
        <table className="w-full text-sm">
          <thead>
            <tr className="text-left">
              <th className="py-2">Started</th>
              <th>Status</th>
              <th>Severity</th>
              <th>Alert</th>
              <th>PR</th>
            </tr>
          </thead>
          <tbody>
            {rows.map(({ run, alert, pr }) => (
              <tr key={run.id} className="border-t align-top">
                <td className="whitespace-nowrap py-2">
                  {new Date(run.startedAt).toLocaleString()}
                </td>
                <td className="font-mono">{run.status}</td>
                <td>{run.severity ?? "—"}</td>
                <td className="max-w-md truncate">{alert.title}</td>
                <td>
                  {pr ? (
                    <a
                      className="text-blue-600 underline"
                      href={pr.url}
                      target="_blank"
                      rel="noreferrer"
                    >
                      #{pr.number} {pr.isDraft ? "(draft)" : ""}
                    </a>
                  ) : (
                    "—"
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}
