import { useQuery } from "@tanstack/react-query";
import { createFileRoute, Link } from "@tanstack/react-router";

import { ManualUrlTrigger } from "@/components/triggers/manual-url-trigger";
import { trpc } from "@/utils/trpc";

export const Route = createFileRoute("/runs/")({
  component: RunsPage,
});

function RunsPage() {
  const list = useQuery(trpc.runs.list.queryOptions({ limit: 50 }));
  const rows = list.data ?? [];

  return (
    <div className="mx-auto flex max-w-5xl flex-col gap-6 p-6">
      <header>
        <h1 className="font-semibold text-2xl">Runs</h1>
        <p className="text-sm text-zinc-500">
          Auto-generated by source webhooks / polling. Use the URL trigger below to dry-run the
          pipeline against a specific issue without waiting for a real alert.
        </p>
      </header>

      <ManualUrlTrigger />

      {list.isLoading ? (
        <p className="text-sm text-zinc-500">Loading…</p>
      ) : list.error ? (
        <p className="text-red-300 text-sm">{list.error.message}</p>
      ) : rows.length === 0 ? (
        <p className="rounded-md border border-dashed p-8 text-center text-sm text-zinc-500">
          No runs yet. Trigger one above or wait for the next webhook arrival.
        </p>
      ) : (
        <table className="w-full text-sm">
          <thead>
            <tr className="text-left">
              <th className="py-2">Started</th>
              <th>Status</th>
              <th>Severity</th>
              <th>Alert</th>
              <th>PR</th>
            </tr>
          </thead>
          <tbody>
            {rows.map(({ run, alert, pr }) => (
              <tr key={run.id} className="cursor-pointer border-t align-top hover:bg-zinc-900/40">
                <td className="whitespace-nowrap py-2">
                  <Link to="/runs/$id" params={{ id: run.id }} className="block">
                    {new Date(run.startedAt).toLocaleString()}
                  </Link>
                </td>
                <td className="font-mono">
                  <Link to="/runs/$id" params={{ id: run.id }} className="block">
                    {run.status}
                  </Link>
                </td>
                <td>
                  <Link to="/runs/$id" params={{ id: run.id }} className="block">
                    {run.severity ?? "—"}
                  </Link>
                </td>
                <td className="max-w-md truncate">
                  <Link to="/runs/$id" params={{ id: run.id }} className="block">
                    {alert.title}
                  </Link>
                </td>
                <td className="space-x-3 whitespace-nowrap">
                  {pr ? (
                    <a
                      className="text-blue-400 underline"
                      href={pr.url}
                      target="_blank"
                      rel="noreferrer"
                    >
                      PR #{pr.number}
                      {pr.isDraft ? " (draft)" : ""}
                    </a>
                  ) : null}
                  <Link
                    to="/runs/$id"
                    params={{ id: run.id }}
                    className="text-zinc-400 underline hover:text-zinc-200"
                  >
                    Logs
                  </Link>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}
