name: sentry-fixer-bot

services:
  postgres:
    image: postgres
    container_name: sentry-fixer-bot-postgres
    environment:
      POSTGRES_DB: sentry-fixer-bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - sentry-fixer-bot_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  sentry-fixer-bot_postgres_data:
